version: '3'

services:
    nginx:
        image: nginx:latest
        volumes:
            - ./:/var/www
            - ./_docker/nginx/:/etc/nginx/conf.d/
            - ./_docker/logs/nginx:/var/log/nginx
        ports:
            - "9090:80"
        container_name: project_nginx
        restart: unless-stopped
        depends_on:
            - app

    app:
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
            args:
                USER_ID: 1000
                GROUP_ID: 1000
        #user: "${USER_ID}:${GROUP_ID}"
        security_opt:
            - no-new-privileges:true
        tmpfs:
            - /tmp
            - /var/run
        volumes:
            - ./:/var/www
        extra_hosts:
            - "host.docker.internal:host-gateway"
        environment:
            PHP_IDE_CONFIG: "serverName=docker-cli"
        container_name: project_app
        restart: unless-stopped
        depends_on:
            - db

    db:
        image: mysql:8.0
        restart: always
        volumes:
            - ./tmp/db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "9091:3306"
        container_name: project_db

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            PMA_PORT: 3306
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: root
        depends_on:
            - db
        ports:
            - "3001:80"
        restart: unless-stopped
        container_name: project_phpmyadmin

    node:
        image: node:18
        container_name: project_node
        working_dir: /var/www
        environment:
            - NODE_ENV=development
        volumes:
            - ./:/var/www
        command: "tail -f /dev/null"
        ports:
            - "5171:5171"
        restart: unless-stopped
        depends_on:
            - app
